### ISSUE TITLE
device registration with sitetoken

### ISSUE THREAD

**Issue by gogogeNinja** [sitewhere/sitewhere-android#3]
hi Derek,
I'm studying the device registration part of code, and I notice the Android didn't specific stie token when it sending the registration request through MQTT, then the server use the first site automatically.
Will we have the function that the sitewhere server can support the device registration with site token? Thanks.

**Comment by derekadams** [comment]
We need to add that functionality. The current registration request implementation does not pass the site token and the protocol buffer definition does not include the site token field either. It should be easy enough to fix the problem, so we will add it to the list for the 1.0.2 release. Thanks for reporting the issue.

**Comment by derekadams** [comment]
I verified that you are correct that passing an empty JSON array as the metadata in updates does not work. It appears to be a bug in the common update logic. I've added two Jira issues for the 1.0.2 release so that we make sure the problems are taken care of. Thanks for reporting the problem!

https://sitewhere.atlassian.net/browse/SITEWHERE-145
https://sitewhere.atlassian.net/browse/SITEWHERE-146
